//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_1
    {
        public int MaSach { get; set; }
        public string TenSach { get; set; }
        public string Giá { get; set; }
        public string TG { get; set; }
        public Nullable<int> SL { get; set; }
    }
}
